### ISSUE TITLE
Improve the display of the "Ready" state

### ISSUE THREAD

**Issue by lgarron** [cubing/timer.cubing.net#13]
@jfly says the green pulse is too slow, and I agree.

For now, I think the simplest is just to change the color of the text (or background) just once.
Alternatively, maybe I can manage to fit in an unobtrusive indicator like the "ready" light on a Stackmat timer.

**Comment by ToastyKen** [comment]
Any reason why not just solid green?

**Comment by lgarron** [comment]
> Any reason why not just solid green?

I wanted something more active, because I learned from http://www.cubing.net/inspection/ that a static does not make it clear that the timer will start when you let go. Maybe it makes less sense for a personal timer, where you don't have to wait on someone else before starting, and a failure to start is not as critical.
